trigger:
  - master
  - refs/tags/*

pr:
  - master

variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 120
      areaPath: 'DevDiv\Xamarin SDK\Android'
      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots https://aka.ms/xamarin-android-commercial-d16-6-macos
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
            boots https://aka.ms/xamarin-android-commercial-d16-6-windows
          condition: eq(variables['System.JobName'], 'windows')
      tools:
        - 'xamarin.androidbinderator.tool': '0.4.2'
        - 'xamarin.androidx.migration.tool': '1.0.6.2'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v1.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
